version: '2'
services:
  lal:
    container_name: lal
    #command: ./bin/lalpp 0.0.0.0 5001
    #command: psql postgresql://lal:lal@laldb:5432/lal -c "select * from post"
    command: ./init
    build: ./
    depends_on:
    - laldb
    ports:
    - "5000:5001"
    volumes:
    - "./:/usr/src/lal"
    environment:
      DEBUG: indeed

  laldb:
    container_name: laldb
    image: postgres:10
    environment:
      POSTGRES_USER: lal
      POSTGRES_PASSWORD: lal
    expose:
    - "5432"
    volumes:
    - ${PWD}/data:/var/lib/postgresql/data

